wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.13.11
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.10.9
    start_time: 1678599013.579529
    t:
      1:
      - 1
      - 55
      2:
      - 1
      - 55
      3:
      - 2
      - 23
      - 37
      4: 3.10.9
      5: 0.13.11
      8:
      - 4
      - 5
    visualize:
      rel_error_hist:
        panel_config:
          fieldSettings:
            value: scores
          panelDefId: wandb/histogram/v0
          stringSettings:
            title: zjefj
          transform:
            name: tableWithLeafColNames
          userQuery:
            queryFields:
            - args:
              - name: runSets
                value: ${runSets}
              fields:
              - fields: []
                name: id
              - fields: []
                name: name
              - fields: []
                name: _defaultColorIndex
              - args:
                - name: tableKey
                  value: rel_error_hist_table
                fields: []
                name: summaryTable
              name: runSets
        panel_type: Vega2
batch_size:
  desc: null
  value: 1024
dim:
  desc: null
  value: 16
h_dim:
  desc: null
  value: 64
lr:
  desc: null
  value: 0.001
